INSERT INTO news (headline, description, publication_time)
VALUES ('Ukrainian News', 'Ukrainian News description', DATE_FORMAT(NOW(), '%Y-%m-%d') + INTERVAL 1 HOUR),
       ('New Zealand News', 'New Zealand News description', DATE_FORMAT(NOW(), '%Y-%m-%d') + INTERVAL 2 HOUR),
       ('Singaporean News', 'Singaporean News description', DATE_FORMAT(NOW(), '%Y-%m-%d') + INTERVAL 2 HOUR),
       ('Malaysian News', 'Malaysian News description', DATE_FORMAT(NOW(), '%Y-%m-%d') + INTERVAL 2 HOUR),
       ('USA News', 'USA News description', DATE_FORMAT(NOW(), '%Y-%m-%d') + INTERVAL 6 HOUR),
       ('United Kingdom News', 'United Kingdom News description', DATE_FORMAT(NOW(), '%Y-%m-%d') + INTERVAL 6 HOUR),
       ('Canadian News', 'Canadian News description', DATE_FORMAT(NOW(), '%Y-%m-%d') + INTERVAL 6 HOUR),
       ('German News', 'German News description', DATE_FORMAT(NOW(), '%Y-%m-%d') + INTERVAL 6 HOUR),
       ('French News', 'French News description', DATE_FORMAT(NOW(), '%Y-%m-%d') + INTERVAL 6 HOUR),
       ('Irish News', 'Irish News description', DATE_FORMAT(NOW(), '%Y-%m-%d') + INTERVAL 8 HOUR),
       ('Indonesian News', 'Indonesian News description', DATE_FORMAT(NOW(), '%Y-%m-%d') + INTERVAL 8 HOUR),
       ('Pakistani News', 'Pakistani News description', DATE_FORMAT(NOW(), '%Y-%m-%d') + INTERVAL 8 HOUR),
       ('Swiss News', 'Swiss News description', DATE_FORMAT(NOW(), '%Y-%m-%d') + INTERVAL 10 HOUR),
       ('Belgian News', 'Belgian News description', DATE_FORMAT(NOW(), '%Y-%m-%d') + INTERVAL 10 HOUR),
       ('Portuguese News', 'Portuguese News description', DATE_FORMAT(NOW(), '%Y-%m-%d') + INTERVAL 10 HOUR),
       ('Greek News', 'Greek News description', DATE_FORMAT(NOW(), '%Y-%m-%d') + INTERVAL 10 HOUR),
       ('Spanish News', 'Spanish News description', DATE_FORMAT(NOW(), '%Y-%m-%d') + INTERVAL 12 HOUR),
       ('Italian News', 'Italian News description', DATE_FORMAT(NOW(), '%Y-%m-%d') + INTERVAL 12 HOUR),
       ('Japanese News', 'Japanese News description', DATE_FORMAT(NOW(), '%Y-%m-%d') + INTERVAL 12 HOUR),
       ('Chinese News', 'Chinese News description', DATE_FORMAT(NOW(), '%Y-%m-%d') + INTERVAL 12 HOUR),
       ('Russian News', 'Russian News description', DATE_FORMAT(NOW(), '%Y-%m-%d') + INTERVAL 12 HOUR),
       ('Brazilian News', 'Brazilian News description', DATE_FORMAT(NOW(), '%Y-%m-%d') + INTERVAL 12 HOUR),
       ('Indian News', 'Indian News description', DATE_FORMAT(NOW(), '%Y-%m-%d') + INTERVAL 12 HOUR),
       ('Australian News', 'Australian News description', DATE_FORMAT(NOW(), '%Y-%m-%d') + INTERVAL 15 HOUR),
       ('Mexican News', 'Mexican News description', DATE_FORMAT(NOW(), '%Y-%m-%d') + INTERVAL 15 HOUR),
       ('South African News', 'South African News description', DATE_FORMAT(NOW(), '%Y-%m-%d') + INTERVAL 15 HOUR),
       ('Egyptian News', 'Egyptian News description', DATE_FORMAT(NOW(), '%Y-%m-%d') + INTERVAL 15 HOUR),
       ('Argentinian News', 'Argentinian News description', DATE_FORMAT(NOW(), '%Y-%m-%d') + INTERVAL 17 HOUR),
       ('Saudi Arabian News', 'Saudi Arabian News description', DATE_FORMAT(NOW(), '%Y-%m-%d') + INTERVAL 17 HOUR),
       ('South Korean News', 'South Korean News description', DATE_FORMAT(NOW(), '%Y-%m-%d') + INTERVAL 17 HOUR),
       ('Vietnamese News', 'Vietnamese News description', DATE_FORMAT(NOW(), '%Y-%m-%d') + INTERVAL 17 HOUR),
       ('Turkish News', 'Turkish News description', DATE_FORMAT(NOW(), '%Y-%m-%d') + INTERVAL 17 HOUR),
       ('Polish News', 'Polish News description', DATE_FORMAT(NOW(), '%Y-%m-%d') + INTERVAL 20 HOUR),
       ('Dutch News', 'Dutch News description', DATE_FORMAT(NOW(), '%Y-%m-%d') + INTERVAL 20 HOUR),
       ('Swedish News', 'Swedish News description', DATE_FORMAT(NOW(), '%Y-%m-%d') + INTERVAL 20 HOUR),
       ('Norwegian News', 'Norwegian News description', DATE_FORMAT(NOW(), '%Y-%m-%d') + INTERVAL 21 HOUR),
       ('Finnish News', 'Finnish News description', DATE_FORMAT(NOW(), '%Y-%m-%d') + INTERVAL 21 HOUR),
       ('Danish News', 'Danish News description', DATE_FORMAT(NOW(), '%Y-%m-%d') + INTERVAL 21 HOUR),
       ('Austrian News', 'Austrian News description', DATE_FORMAT(NOW(), '%Y-%m-%d') + INTERVAL 21 HOUR),
       ('Bangladeshi News', 'Bangladeshi News description', DATE_FORMAT(NOW(), '%Y-%m-%d') + INTERVAL 23 HOUR);
