version: '3.9'
services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: news_service_schema
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - news-network
    restart: unless-stopped

networks:
  news-network:
    driver: bridge

volumes:
  mysql_data: